### ISSUE TITLE
Error when building with Xcode Version 14.0 beta 3 (14A5270f)

### ISSUE THREAD

**Issue by TheApApp** [youjinp/SwiftUIKit#33]
Receiving the following build errors:

1) /Users/dev/Library/Developer/Xcode/DerivedData/AppName-hbeklfnuvwbepyaujkierepomydw/SourcePackages/checkouts/SwiftUIKit/Sources/SwiftUIKit/views/ContactPicker.swift:73:24: error build: Inheritance from non-protocol, non-class type 'ContactPicker.Coordinator' (aka 'any Coordinator')

2) /Users/dev/Library/Developer/Xcode/DerivedData/AppName-hbeklfnuvwbepyaujkierepomydw/SourcePackages/checkouts/SwiftUIKit/Sources/SwiftUIKit/views/ContactPicker.swift:91:24: error build: Inheritance from non-protocol, non-class type 'ContactPicker.Coordinator' (aka 'any Coordinator')

**Comment by TheApApp** [comment]
Note it compiles fine on Xcode 13.4.1 (13F100)

**Comment by youjinp** [comment]
Yep, this is acknowledged with #32. I'd appreciate if you could make the changes suggested. Haven't gotten around to Xcode 14 yet 🙏

**Comment by TheApApp** [comment]
Thanks for the heads up! (not a git expert with Xcode, and Can't figure out how to update the package dependency for the proposed fix.  Will keep an eye out.
